name: Build Yantra Pro

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the Pro APK
        run: |
          touch local.properties
          chmod +x gradlew
          ./gradlew assembleProDebug

      - name: Upload the APK for Download
        uses: actions/upload-artifact@v4
        with:
          name: Yantra-Pro-APK
          path: app/build/outputs/apk/**/*.apk
