name: Build Yantra Pro

on: 
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Missing Properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "WEATHER_API_KEY=dummy_key" >> local.properties
          echo "MAPS_API_KEY=dummy_key" >> local.properties
          echo "NAGA_API_KEY=dummy_key" >> local.properties

      - name: Build Pro APK
        run: |
          chmod +x gradlew
          ./gradlew assembleProDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Yantra-Pro-APK
          path: app/build/outputs/apk/pro/debug/*.apk
